package com.qpay.user.infrastructure;
import com.qpay.user.application.UserView;import com.qpay.user.domain.KycStatus;import com.qpay.user.security.DeviceTokenProtector;import org.springframework.jdbc.core.simple.JdbcClient;import org.springframework.stereotype.Repository;import java.time.*;import java.util.*;
@Repository public class UserRepository {
 private final JdbcClient jdbc;public UserRepository(JdbcClient jdbc){this.jdbc=jdbc;}
 public UserView create(UUID id,String name,String email,String phone,String locale){Instant now=Instant.now();jdbc.sql("INSERT INTO app_user(id,status,display_name,email_normalized,phone_e164,kyc_status,locale,version,created_at,updated_at) VALUES(UUID_TO_BIN(:id,1),'ACTIVE',:name,:email,:phone,'NOT_STARTED',:locale,0,:now,:now)").param("id",id.toString()).param("name",name).param("email",email).param("phone",phone).param("locale",locale).param("now",now).update();event(id,"user.created.v1",now);return find(id).orElseThrow();}
 public Optional<UserView> find(UUID id){return jdbc.sql("SELECT BIN_TO_UUID(id,1) id,status,display_name,email_normalized,phone_e164,kyc_status,locale,version,created_at,updated_at FROM app_user WHERE id=UUID_TO_BIN(:id,1)").param("id",id.toString()).query((r,n)->new UserView(UUID.fromString(r.getString("id")),r.getString("status"),r.getString("display_name"),r.getString("email_normalized"),r.getString("phone_e164"),KycStatus.valueOf(r.getString("kyc_status")),r.getString("locale"),r.getLong("version"),r.getTimestamp("created_at").toInstant(),r.getTimestamp("updated_at").toInstant())).optional();}
 public UserView update(UUID id,String name,String email,String phone,String locale,long version){int changed=jdbc.sql("UPDATE app_user SET display_name=:name,email_normalized=:email,phone_e164=:phone,locale=:locale,version=version+1,updated_at=CURRENT_TIMESTAMP(6) WHERE id=UUID_TO_BIN(:id,1) AND version=:version").param("name",name).param("email",email).param("phone",phone).param("locale",locale).param("id",id.toString()).param("version",version).update();if(changed!=1)throw new IllegalStateException("concurrent user update");return find(id).orElseThrow();}
 public UserView transitionKyc(UUID id,KycStatus target,String reference){UserView current=jdbc.sql("SELECT BIN_TO_UUID(id,1) id,status,display_name,email_normalized,phone_e164,kyc_status,locale,version,created_at,updated_at FROM app_user WHERE id=UUID_TO_BIN(:id,1) FOR UPDATE").param("id",id.toString()).query((r,n)->new UserView(UUID.fromString(r.getString("id")),r.getString("status"),r.getString("display_name"),r.getString("email_normalized"),r.getString("phone_e164"),KycStatus.valueOf(r.getString("kyc_status")),r.getString("locale"),r.getLong("version"),r.getTimestamp("created_at").toInstant(),r.getTimestamp("updated_at").toInstant())).single();current.kycStatus().requireTransitionTo(target);jdbc.sql("UPDATE app_user SET kyc_status=:status,kyc_reference=:reference,version=version+1,updated_at=CURRENT_TIMESTAMP(6) WHERE id=UUID_TO_BIN(:id,1)").param("status",target.name()).param("reference",reference).param("id",id.toString()).update();event(id,"user.kyc-"+target.name().toLowerCase(Locale.ROOT)+".v1",Instant.now());return find(id).orElseThrow();}
 public DeviceRegistration registerDevice(UUID user,String platform,DeviceTokenProtector.ProtectedToken token){UUID id=UUID.randomUUID();jdbc.sql("INSERT INTO device_token(id,user_id,platform,token_ciphertext,token_nonce,token_key_version,token_hash,token_mask,status,last_seen_at,created_at) VALUES(UUID_TO_BIN(:id,1),UUID_TO_BIN(:user,1),:platform,:cipher,:nonce,:keyVersion,:hash,:mask,'ACTIVE',CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6)) ON DUPLICATE KEY UPDATE user_id=VALUES(user_id),platform=VALUES(platform),status='ACTIVE',last_seen_at=CURRENT_TIMESTAMP(6),revoked_at=NULL").param("id",id.toString()).param("user",user.toString()).param("platform",platform).param("cipher",token.ciphertext()).param("nonce",token.nonce()).param("keyVersion",token.keyVersion()).param("hash",token.hash()).param("mask",token.mask()).update();return jdbc.sql("SELECT BIN_TO_UUID(id,1) id,token_mask FROM device_token WHERE token_hash=:hash").param("hash",token.hash()).query((r,n)->new DeviceRegistration(UUID.fromString(r.getString("id")),r.getString("token_mask"))).single();}
 public void revokeDevice(UUID user,UUID device){if(jdbc.sql("UPDATE device_token SET status='REVOKED',revoked_at=CURRENT_TIMESTAMP(6) WHERE id=UUID_TO_BIN(:device,1) AND user_id=UUID_TO_BIN(:user,1) AND status='ACTIVE'").param("device",device.toString()).param("user",user.toString()).update()!=1)throw new IllegalArgumentException("active device token not found");}
 public void preference(UUID user,String event,boolean push,boolean email,boolean sms){jdbc.sql("INSERT INTO notification_preference(user_id,event_type,push_enabled,email_enabled,sms_enabled,updated_at) VALUES(UUID_TO_BIN(:user,1),:event,:push,:email,:sms,CURRENT_TIMESTAMP(6)) ON DUPLICATE KEY UPDATE push_enabled=VALUES(push_enabled),email_enabled=VALUES(email_enabled),sms_enabled=VALUES(sms_enabled),updated_at=CURRENT_TIMESTAMP(6)").param("user",user.toString()).param("event",event).param("push",push).param("email",email).param("sms",sms).update();}
 private void event(UUID id,String type,Instant now){jdbc.sql("INSERT INTO outbox_event(id,aggregate_id,event_type,partition_key,payload,occurred_at,publish_attempts) VALUES(UUID_TO_BIN(:event,1),UUID_TO_BIN(:id,1),:type,:key,JSON_OBJECT('userId',:key),:now,0)").param("event",UUID.randomUUID().toString()).param("id",id.toString()).param("type",type).param("key",id.toString()).param("now",now).update();}
 public record DeviceRegistration(UUID id,String tokenMask){}
}
