package com.qpay.payment.infrastructure;
import com.qpay.payment.application.RefundView;import com.qpay.payment.domain.RefundStatus;import org.springframework.jdbc.core.simple.JdbcClient;import org.springframework.stereotype.Repository;import java.time.*;import java.util.*;
@Repository public class RefundRepository {
 private final JdbcClient jdbc;public RefundRepository(JdbcClient jdbc){this.jdbc=jdbc;}
 public Reservation reserve(UUID merchant,UUID paymentId,String reference,long amount){var payment=jdbc.sql("SELECT BIN_TO_UUID(merchant_id,1) merchant_id,BIN_TO_UUID(wallet_id,1) wallet_id,amount_minor,currency,status,provider_reference FROM payment WHERE id=UUID_TO_BIN(:id,1) FOR UPDATE").param("id",paymentId.toString()).query((r,n)->new Original(UUID.fromString(r.getString("merchant_id")),UUID.fromString(r.getString("wallet_id")),r.getLong("amount_minor"),r.getString("currency"),r.getString("status"),r.getString("provider_reference"))).optional().orElseThrow(()->new IllegalArgumentException("payment not found"));if(!merchant.equals(payment.merchantId))throw new SecurityException("payment does not belong to merchant");if(!"SUCCEEDED".equals(payment.status))throw new IllegalStateException("only successful payments can be refunded");var existing=findByReference(paymentId,reference);if(existing.isPresent()){if(existing.get().amountMinor()!=amount)throw new IllegalArgumentException("refund reference was reused with a different amount");return new Reservation(existing.get(),payment.providerReference,true);}Long reserved=jdbc.sql("SELECT COALESCE(SUM(amount_minor),0) FROM refund WHERE payment_id=UUID_TO_BIN(:id,1) AND status IN('PENDING','PROCESSING','SUCCEEDED')").param("id",paymentId.toString()).query(Long.class).single();if(amount<=0||Math.addExact(reserved,amount)>payment.amount)throw new IllegalArgumentException("refund exceeds remaining refundable amount");UUID id=UUID.randomUUID();Instant now=Instant.now();jdbc.sql("INSERT INTO refund(id,payment_id,merchant_id,wallet_id,merchant_reference,amount_minor,currency,status,version,created_at,updated_at) VALUES(UUID_TO_BIN(:id,1),UUID_TO_BIN(:payment,1),UUID_TO_BIN(:merchant,1),UUID_TO_BIN(:wallet,1),:reference,:amount,:currency,'PENDING',0,:now,:now)").param("id",id.toString()).param("payment",paymentId.toString()).param("merchant",merchant.toString()).param("wallet",payment.walletId.toString()).param("reference",reference).param("amount",amount).param("currency",payment.currency).param("now",now).update();return new Reservation(find(id).orElseThrow(),payment.providerReference,false);}
 public void processing(UUID id){transition(id,RefundStatus.PENDING,RefundStatus.PROCESSING,null,null,null);}
 public RefundView complete(UUID id,String provider,String providerRef,boolean success,String failure){transition(id,RefundStatus.PROCESSING,success?RefundStatus.SUCCEEDED:RefundStatus.FAILED,provider,providerRef,failure);RefundView refund=find(id).orElseThrow();if(success)event(refund);return refund;}
 private void transition(UUID id,RefundStatus from,RefundStatus to,String provider,String providerRef,String failure){from.requireTransitionTo(to);int changed=jdbc.sql("UPDATE refund SET status=:to,provider_code=COALESCE(:provider,provider_code),provider_reference=COALESCE(:providerRef,provider_reference),failure_code=:failure,version=version+1,updated_at=CURRENT_TIMESTAMP(6),completed_at=IF(:terminal,CURRENT_TIMESTAMP(6),completed_at) WHERE id=UUID_TO_BIN(:id,1) AND status=:from").param("to",to.name()).param("provider",provider).param("providerRef",providerRef).param("failure",failure).param("terminal",to==RefundStatus.SUCCEEDED).param("id",id.toString()).param("from",from.name()).update();if(changed!=1)throw new IllegalStateException("concurrent refund transition");}
 public Optional<RefundView> find(UUID id){return query("id=UUID_TO_BIN(:value,1)",id.toString());}private Optional<RefundView> findByReference(UUID payment,String reference){return jdbc.sql(select()+" WHERE payment_id=UUID_TO_BIN(:payment,1) AND merchant_reference=:reference").param("payment",payment.toString()).param("reference",reference).query(this::map).optional();}private Optional<RefundView> query(String where,String value){return jdbc.sql(select()+" WHERE "+where).param("value",value).query(this::map).optional();}
 private String select(){return "SELECT BIN_TO_UUID(id,1) id,BIN_TO_UUID(payment_id,1) payment_id,BIN_TO_UUID(merchant_id,1) merchant_id,BIN_TO_UUID(wallet_id,1) wallet_id,merchant_reference,amount_minor,currency,status,provider_reference,failure_code,created_at,updated_at FROM refund";}private RefundView map(java.sql.ResultSet r,int n)throws java.sql.SQLException{return new RefundView(UUID.fromString(r.getString("id")),UUID.fromString(r.getString("payment_id")),UUID.fromString(r.getString("merchant_id")),UUID.fromString(r.getString("wallet_id")),r.getString("merchant_reference"),r.getLong("amount_minor"),Currency.getInstance(r.getString("currency")),RefundStatus.valueOf(r.getString("status")),r.getString("provider_reference"),r.getString("failure_code"),r.getTimestamp("created_at").toInstant(),r.getTimestamp("updated_at").toInstant());}
 private void event(RefundView r){jdbc.sql("INSERT INTO outbox_event(id,aggregate_type,aggregate_id,event_type,event_version,partition_key,payload,occurred_at,publish_attempts) VALUES(UUID_TO_BIN(:event,1),'REFUND',UUID_TO_BIN(:id,1),'refund.succeeded.v1',1,:key,JSON_OBJECT('refundId',:key,'paymentId',:payment,'merchantId',:merchant,'walletId',:wallet,'merchantReference',:reference,'amountMinor',:amount,'currency',:currency),CURRENT_TIMESTAMP(6),0)").param("event",UUID.randomUUID().toString()).param("id",r.id().toString()).param("key",r.id().toString()).param("payment",r.paymentId().toString()).param("merchant",r.merchantId().toString()).param("wallet",r.walletId().toString()).param("reference",r.merchantReference()).param("amount",r.amountMinor()).param("currency",r.currency().getCurrencyCode()).update();}
 public record Reservation(RefundView refund,String originalProviderReference,boolean replay){}private record Original(UUID merchantId,UUID walletId,long amount,String currency,String status,String providerReference){}
}
