package com.qpay.payment.infrastructure;
import com.qpay.payment.application.UtilityPaymentView;import com.qpay.payment.domain.UtilityPaymentStatus;import org.springframework.jdbc.core.simple.JdbcClient;import org.springframework.stereotype.Repository;import java.time.*;import java.util.*;
@Repository public class UtilityPaymentRepository {
 private final JdbcClient jdbc;public UtilityPaymentRepository(JdbcClient jdbc){this.jdbc=jdbc;}
 public Reservation create(UUID merchant,UUID wallet,String reference,String biller,String consumer,long amount,long fee,String currency){var existing=findByReference(merchant,reference);if(existing.isPresent()){var e=existing.get();if(!e.walletId().equals(wallet)||e.amountMinor()!=amount||!e.billerCode().equals(biller)||!e.consumerReference().equals(consumer))throw new IllegalArgumentException("utility reference was reused with different data");return new Reservation(e,true);}UUID id=UUID.randomUUID();Instant now=Instant.now();jdbc.sql("INSERT INTO utility_payment(id,merchant_id,wallet_id,merchant_reference,biller_code,consumer_reference,amount_minor,fee_minor,currency,status,version,created_at,updated_at) VALUES(UUID_TO_BIN(:id,1),UUID_TO_BIN(:merchant,1),UUID_TO_BIN(:wallet,1),:reference,:biller,:consumer,:amount,:fee,:currency,'CREATED',0,:now,:now)").param("id",id.toString()).param("merchant",merchant.toString()).param("wallet",wallet.toString()).param("reference",reference).param("biller",biller).param("consumer",consumer).param("amount",amount).param("fee",fee).param("currency",currency).param("now",now).update();event(id,"utility-payment.created.v1");return new Reservation(find(id).orElseThrow(),false);}
 public UtilityPaymentView transition(UUID id,UtilityPaymentStatus from,UtilityPaymentStatus to,UUID hold,String providerRef,String failure){from.requireTransitionTo(to);int changed=jdbc.sql("UPDATE utility_payment SET status=:to,hold_id=COALESCE(UUID_TO_BIN(:hold,1),hold_id),provider_reference=COALESCE(:providerRef,provider_reference),failure_code=:failure,version=version+1,updated_at=CURRENT_TIMESTAMP(6),completed_at=IF(:terminal,CURRENT_TIMESTAMP(6),completed_at) WHERE id=UUID_TO_BIN(:id,1) AND status=:from").param("to",to.name()).param("hold",hold==null?null:hold.toString()).param("providerRef",providerRef).param("failure",failure).param("terminal",to==UtilityPaymentStatus.SUCCEEDED).param("id",id.toString()).param("from",from.name()).update();if(changed!=1)throw new IllegalStateException("concurrent utility-payment transition");event(id,"utility-payment."+to.name().toLowerCase(Locale.ROOT).replace('_','-')+".v1");return find(id).orElseThrow();}
 public Optional<UtilityPaymentView> find(UUID id){return jdbc.sql(select()+" WHERE id=UUID_TO_BIN(:id,1)").param("id",id.toString()).query(this::map).optional();}private Optional<UtilityPaymentView> findByReference(UUID merchant,String reference){return jdbc.sql(select()+" WHERE merchant_id=UUID_TO_BIN(:merchant,1) AND merchant_reference=:reference").param("merchant",merchant.toString()).param("reference",reference).query(this::map).optional();}
 private String select(){return "SELECT BIN_TO_UUID(id,1) id,BIN_TO_UUID(merchant_id,1) merchant_id,BIN_TO_UUID(wallet_id,1) wallet_id,merchant_reference,biller_code,consumer_reference,amount_minor,fee_minor,currency,status,BIN_TO_UUID(hold_id,1) hold_id,provider_reference,failure_code,created_at,updated_at FROM utility_payment";}private UtilityPaymentView map(java.sql.ResultSet r,int n)throws java.sql.SQLException{return new UtilityPaymentView(UUID.fromString(r.getString("id")),UUID.fromString(r.getString("merchant_id")),UUID.fromString(r.getString("wallet_id")),r.getString("merchant_reference"),r.getString("biller_code"),r.getString("consumer_reference"),r.getLong("amount_minor"),r.getLong("fee_minor"),Currency.getInstance(r.getString("currency")),UtilityPaymentStatus.valueOf(r.getString("status")),r.getString("hold_id")==null?null:UUID.fromString(r.getString("hold_id")),r.getString("provider_reference"),r.getString("failure_code"),r.getTimestamp("created_at").toInstant(),r.getTimestamp("updated_at").toInstant());}
 private void event(UUID id,String type){jdbc.sql("INSERT INTO outbox_event(id,aggregate_type,aggregate_id,event_type,event_version,partition_key,payload,occurred_at,publish_attempts) VALUES(UUID_TO_BIN(:event,1),'UTILITY_PAYMENT',UUID_TO_BIN(:id,1),:type,1,:key,JSON_OBJECT('utilityPaymentId',:key),CURRENT_TIMESTAMP(6),0)").param("event",UUID.randomUUID().toString()).param("id",id.toString()).param("type",type).param("key",id.toString()).update();}
 public record Reservation(UtilityPaymentView payment,boolean replay){}
}
