package com.qpay.auth.application;
import org.springframework.beans.factory.annotation.Value;import org.springframework.jdbc.core.simple.JdbcClient;import org.springframework.security.crypto.password.PasswordEncoder;import org.springframework.security.oauth2.jwt.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.nio.charset.StandardCharsets;import java.security.*;import java.time.*;import java.util.*;
@Service public class AuthService {
 private final JdbcClient jdbc;private final PasswordEncoder passwords;private final JwtEncoder encoder;private final String issuer;private final SecureRandom random=new SecureRandom();
 public AuthService(JdbcClient jdbc,PasswordEncoder passwords,JwtEncoder encoder,@Value("${qpay.jwt.issuer:http://localhost:8081}")String issuer){this.jdbc=jdbc;this.passwords=passwords;this.encoder=encoder;this.issuer=issuer;}
 @Transactional public Tokens login(String login,String password){Principal p=find(login);if(!"ACTIVE".equals(p.status)||!passwords.matches(password,p.hash))throw new SecurityException("invalid credentials");return issue(p,UUID.randomUUID());}
 @Transactional public Tokens refresh(String raw){byte[] hash=hash(raw);var row=jdbc.sql("SELECT BIN_TO_UUID(t.id,1) token_id,BIN_TO_UUID(t.family_id,1) family_id,p.login_name,p.password_hash,p.status,BIN_TO_UUID(p.id,1) principal_id,BIN_TO_UUID(p.external_owner_id,1) owner_id FROM refresh_token t JOIN principal p ON p.id=t.principal_id WHERE t.token_hash=:hash FOR UPDATE").param("hash",hash).query((r,n)->new Refresh(r.getString("token_id"),r.getString("family_id"),new Principal(UUID.fromString(r.getString("principal_id")),UUID.fromString(r.getString("owner_id")),r.getString("login_name"),r.getString("password_hash"),r.getString("status")))).optional().orElseThrow(()->new SecurityException("invalid refresh token"));int changed=jdbc.sql("UPDATE refresh_token SET used_at=CURRENT_TIMESTAMP(6) WHERE id=UUID_TO_BIN(:id,1) AND used_at IS NULL AND revoked_at IS NULL AND expires_at>CURRENT_TIMESTAMP(6)").param("id",row.tokenId).update();if(changed!=1){jdbc.sql("UPDATE refresh_token SET revoked_at=CURRENT_TIMESTAMP(6) WHERE family_id=UUID_TO_BIN(:family,1) AND revoked_at IS NULL").param("family",row.familyId).update();throw new SecurityException("refresh token reuse detected");}return issue(row.principal,UUID.fromString(row.familyId));}
 private Tokens issue(Principal p,UUID family){Instant now=Instant.now(),expiry=now.plusSeconds(900);List<String> roles=jdbc.sql("SELECT role_code FROM principal_role WHERE principal_id=UUID_TO_BIN(:id,1)").param("id",p.id.toString()).query(String.class).list();JwtClaimsSet claims=JwtClaimsSet.builder().issuer(issuer).subject(p.id.toString()).audience(List.of("qpay-api")).issuedAt(now).expiresAt(expiry).id(UUID.randomUUID().toString()).claim("owner_id",p.owner.toString()).claim("roles",roles).claim("scope",String.join(" ",roles.stream().map(r->r.toLowerCase(Locale.ROOT)).toList())).build();String access=encoder.encode(JwtEncoderParameters.from(claims)).getTokenValue();byte[] bytes=new byte[32];random.nextBytes(bytes);String refresh=Base64.getUrlEncoder().withoutPadding().encodeToString(bytes);jdbc.sql("INSERT INTO refresh_token(id,principal_id,family_id,token_hash,expires_at,created_at) VALUES(UUID_TO_BIN(:id,1),UUID_TO_BIN(:principal,1),UUID_TO_BIN(:family,1),:hash,:expiry,:now)").param("id",UUID.randomUUID().toString()).param("principal",p.id.toString()).param("family",family.toString()).param("hash",hash(refresh)).param("expiry",now.plus(Duration.ofDays(30))).param("now",now).update();return new Tokens(access,refresh,"Bearer",900);}
 private Principal find(String login){return jdbc.sql("SELECT BIN_TO_UUID(id,1) id,BIN_TO_UUID(external_owner_id,1) owner_id,login_name,password_hash,status FROM principal WHERE login_name=:login").param("login",login.toLowerCase(Locale.ROOT)).query((r,n)->new Principal(UUID.fromString(r.getString("id")),UUID.fromString(r.getString("owner_id")),r.getString("login_name"),r.getString("password_hash"),r.getString("status"))).optional().orElseThrow(()->new SecurityException("invalid credentials"));}
 private byte[] hash(String s){try{return MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8));}catch(Exception e){throw new IllegalStateException(e);}}
 public record Tokens(String accessToken,String refreshToken,String tokenType,long expiresIn){}private record Principal(UUID id,UUID owner,String login,String hash,String status){}private record Refresh(String tokenId,String familyId,Principal principal){}
}
