package com.qpay.reconciliation.infrastructure;
import com.qpay.reconciliation.domain.*;import org.springframework.jdbc.core.simple.JdbcClient;import org.springframework.stereotype.Repository;import java.time.*;import java.util.*;
@Repository public class ReconciliationRepository {
 private final JdbcClient jdbc;public ReconciliationRepository(JdbcClient jdbc){this.jdbc=jdbc;}
 public void upsertInternal(String reference,String provider,String providerReference,long amount,String currency,String status,Instant occurredAt){jdbc.sql("INSERT INTO internal_transaction(reference,provider_code,provider_reference,amount_minor,currency,status,occurred_at,updated_at) VALUES(:reference,:provider,:providerRef,:amount,:currency,:status,:occurred,CURRENT_TIMESTAMP(6)) ON DUPLICATE KEY UPDATE provider_reference=VALUES(provider_reference),amount_minor=VALUES(amount_minor),currency=VALUES(currency),status=VALUES(status),occurred_at=VALUES(occurred_at),updated_at=CURRENT_TIMESTAMP(6)").param("reference",reference).param("provider",provider).param("providerRef",providerReference).param("amount",amount).param("currency",currency).param("status",status).param("occurred",occurredAt).update();}
 public UUID start(String provider,LocalDate date,String source,byte[] hash){UUID id=UUID.randomUUID();jdbc.sql("INSERT INTO reconciliation_run(id,provider_code,settlement_date,source_name,source_hash,status,started_at) VALUES(UUID_TO_BIN(:id,1),:provider,:date,:source,:hash,'PROCESSING',CURRENT_TIMESTAMP(6))").param("id",id.toString()).param("provider",provider).param("date",date).param("source",source).param("hash",hash).update();return id;}
 public Optional<TransactionMatcher.InternalRecord> findInternal(String provider,String internalRef,String providerRef){return jdbc.sql("SELECT reference,amount_minor,currency,status FROM internal_transaction WHERE reference=:internal OR (provider_code=:provider AND provider_reference=:providerRef) LIMIT 1").param("internal",internalRef).param("provider",provider).param("providerRef",providerRef).query((r,n)->new TransactionMatcher.InternalRecord(r.getString(1),r.getLong(2),r.getString(3),r.getString(4))).optional();}
 public List<TransactionMatcher.InternalRecord> internalForDate(String provider,LocalDate date){return jdbc.sql("SELECT reference,amount_minor,currency,status FROM internal_transaction WHERE provider_code=:provider AND occurred_at>=:start AND occurred_at<:end").param("provider",provider).param("start",date.atStartOfDay()).param("end",date.plusDays(1).atStartOfDay()).query((r,n)->new TransactionMatcher.InternalRecord(r.getString(1),r.getLong(2),r.getString(3),r.getString(4))).list();}
 public void item(UUID run,TransactionMatcher.ProviderRecord p,TransactionMatcher.InternalRecord i,MatchStatus status){jdbc.sql("INSERT INTO reconciliation_item(id,run_id,provider_reference,internal_reference,provider_amount_minor,internal_amount_minor,currency,provider_status,internal_status,match_status,resolution_status,suspense_required,created_at) VALUES(UUID_TO_BIN(:id,1),UUID_TO_BIN(:run,1),:providerRef,:internalRef,:providerAmount,:internalAmount,:currency,:providerStatus,:internalStatus,:matchStatus,:resolutionStatus,:suspense,CURRENT_TIMESTAMP(6))").param("id",UUID.randomUUID().toString()).param("run",run.toString()).param("providerRef",p==null?null:p.providerReference()).param("internalRef",i!=null?i.reference():p.internalReference()).param("providerAmount",p==null?null:p.amountMinor()).param("internalAmount",i==null?null:i.amountMinor()).param("currency",p!=null?p.currency():i.currency()).param("providerStatus",p==null?null:p.status()).param("internalStatus",i==null?null:i.status()).param("matchStatus",status.name()).param("resolutionStatus",status==MatchStatus.MATCHED?"AUTO_RESOLVED":"OPEN").param("suspense",status!=MatchStatus.MATCHED).update();}
 public void complete(UUID run){jdbc.sql("UPDATE reconciliation_run r SET status='COMPLETED',completed_at=CURRENT_TIMESTAMP(6),total_records=(SELECT COUNT(*) FROM reconciliation_item i WHERE i.run_id=r.id),matched_records=(SELECT COUNT(*) FROM reconciliation_item i WHERE i.run_id=r.id AND i.match_status='MATCHED'),discrepancy_records=(SELECT COUNT(*) FROM reconciliation_item i WHERE i.run_id=r.id AND i.match_status<>'MATCHED') WHERE id=UUID_TO_BIN(:id,1)").param("id",run.toString()).update();}
 public void resolve(UUID item,UUID actor,String newStatus,String reason){String old=jdbc.sql("SELECT resolution_status FROM reconciliation_item WHERE id=UUID_TO_BIN(:id,1) FOR UPDATE").param("id",item.toString()).query(String.class).single();if(!"OPEN".equals(old))throw new IllegalStateException("only open discrepancies can be resolved");jdbc.sql("UPDATE reconciliation_item SET resolution_status=:status,resolved_by=UUID_TO_BIN(:actor,1),resolution_reason=:reason,resolved_at=CURRENT_TIMESTAMP(6) WHERE id=UUID_TO_BIN(:id,1)").param("status",newStatus).param("actor",actor.toString()).param("reason",reason).param("id",item.toString()).update();jdbc.sql("INSERT INTO reconciliation_audit(id,item_id,actor_id,action,previous_status,new_status,reason,occurred_at) VALUES(UUID_TO_BIN(:audit,1),UUID_TO_BIN(:item,1),UUID_TO_BIN(:actor,1),'MANUAL_RESOLUTION',:old,:new,:reason,CURRENT_TIMESTAMP(6))").param("audit",UUID.randomUUID().toString()).param("item",item.toString()).param("actor",actor.toString()).param("old",old).param("new",newStatus).param("reason",reason).update();}
}
