package com.qpay.reconciliation.application;
import com.qpay.reconciliation.domain.*;import com.qpay.reconciliation.infrastructure.ReconciliationRepository;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.io.*;import java.nio.charset.StandardCharsets;import java.security.MessageDigest;import java.time.LocalDate;import java.util.*;
@Service public class ReconciliationService {
 private final ReconciliationRepository repo;public ReconciliationService(ReconciliationRepository repo){this.repo=repo;}
 @Transactional public void recordInternal(String reference,String provider,String providerRef,long amount,String currency,String status,java.time.Instant occurredAt){repo.upsertInternal(reference,provider,providerRef,amount,currency,status,occurredAt);}
 @Transactional public UUID ingest(String provider,LocalDate date,String source,byte[] bytes){UUID run=repo.start(provider,date,source,sha(bytes));Set<String> seen=new HashSet<>();try(var reader=new BufferedReader(new InputStreamReader(new ByteArrayInputStream(bytes),StandardCharsets.UTF_8))){String header=reader.readLine();if(!"providerReference,internalReference,amountMinor,currency,status".equals(header))throw new IllegalArgumentException("unexpected reconciliation CSV header");String line;while((line=reader.readLine())!=null){if(line.isBlank())continue;List<String> fields=parse(line);if(fields.size()!=5)throw new IllegalArgumentException("invalid reconciliation CSV row");var p=new TransactionMatcher.ProviderRecord(fields.get(0),fields.get(1),Long.parseLong(fields.get(2)),fields.get(3),fields.get(4));var internal=repo.findInternal(provider,p.internalReference(),p.providerReference());internal.ifPresent(i->seen.add(i.reference()));repo.item(run,p,internal.orElse(null),TransactionMatcher.match(p,internal));}}catch(IOException e){throw new UncheckedIOException(e);}for(var internal:repo.internalForDate(provider,date))if(!seen.contains(internal.reference()))repo.item(run,null,internal,MatchStatus.MISSING_EXTERNAL);repo.complete(run);return run;}
 @Transactional public void resolve(UUID item,UUID actor,String status,String reason){if(!Set.of("RESOLVED","ACCEPTED_EXCEPTION").contains(status))throw new IllegalArgumentException("invalid resolution status");if(reason==null||reason.isBlank())throw new IllegalArgumentException("resolution reason is required");repo.resolve(item,actor,status,reason);}
 private byte[] sha(byte[] bytes){try{return MessageDigest.getInstance("SHA-256").digest(bytes);}catch(Exception e){throw new IllegalStateException(e);}}
 static List<String> parse(String line){List<String> out=new ArrayList<>();StringBuilder value=new StringBuilder();boolean quoted=false;for(int i=0;i<line.length();i++){char c=line.charAt(i);if(c=='"'){if(quoted&&i+1<line.length()&&line.charAt(i+1)=='"'){value.append('"');i++;}else quoted=!quoted;}else if(c==','&&!quoted){out.add(value.toString());value.setLength(0);}else value.append(c);}if(quoted)throw new IllegalArgumentException("unterminated quoted CSV field");out.add(value.toString());return out;}
}
