package com.qpay.payout.application;
import com.qpay.payout.domain.PayoutStatus;import com.qpay.payout.infrastructure.PayoutRepository;import com.qpay.payout.provider.BankProvider;import com.qpay.payout.security.BankDataCrypto;import com.qpay.payout.wallet.WalletFundsClient;import org.springframework.beans.factory.annotation.Value;import org.springframework.stereotype.Service;import org.springframework.transaction.support.TransactionTemplate;
import java.math.BigInteger;import java.nio.charset.StandardCharsets;import java.security.MessageDigest;import java.util.*;
@Service public class PayoutService {
 private final PayoutRepository repo;private final BankDataCrypto crypto;private final WalletFundsClient wallet;private final BankProvider bank;private final TransactionTemplate tx;private final int feeBps;
 public PayoutService(PayoutRepository repo,BankDataCrypto crypto,WalletFundsClient wallet,BankProvider bank,TransactionTemplate tx,@Value("${qpay.payout.fee-basis-points:100}") int feeBps){this.repo=repo;this.crypto=crypto;this.wallet=wallet;this.bank=bank;this.tx=tx;this.feeBps=feeBps;}
 public UUID createBeneficiary(UUID merchant,String reference,String name,String bankCode,String account){if(account==null||account.length()<4)throw new IllegalArgumentException("invalid account number");return tx.execute(s->repo.createBeneficiary(merchant,reference,name,bankCode,account,crypto));}
 public PayoutView create(UUID merchant,UUID walletId,UUID beneficiary,String reference,long amount,Currency currency,String idem){if(amount<=0||idem==null||idem.length()<8)throw new IllegalArgumentException("positive amount and Idempotency-Key are required");long fee=BigInteger.valueOf(amount).multiply(BigInteger.valueOf(feeBps)).divide(BigInteger.valueOf(10000)).longValueExact();byte[] hash=hash(String.join("\u001f",merchant.toString(),walletId.toString(),beneficiary.toString(),reference,Long.toString(amount),currency.getCurrencyCode()));var reservation=tx.execute(s->repo.createPayout(merchant,walletId,beneficiary,reference,amount,fee,currency.getCurrencyCode(),idem,hash));if(reservation.replay())return reservation.payout();PayoutView p=reservation.payout();UUID holdId=wallet.hold(walletId,p.id().toString(),Math.addExact(amount,fee),currency.getCurrencyCode());try{tx.executeWithoutResult(s->repo.transition(p.id(),PayoutStatus.CREATED,PayoutStatus.FUNDS_HELD,holdId,null,null,null));}catch(RuntimeException e){wallet.release(holdId);throw e;}var result=bank.submit(new BankProvider.Request(p.id(),amount,currency,beneficiary.toString()));if(!result.succeeded()){tx.executeWithoutResult(s->repo.transition(p.id(),PayoutStatus.FUNDS_HELD,PayoutStatus.FAILED,holdId,result.providerCode(),result.providerReference(),result.failureCode()));wallet.release(holdId);tx.executeWithoutResult(s->repo.transition(p.id(),PayoutStatus.FAILED,PayoutStatus.FUNDS_RELEASED,holdId,null,null,result.failureCode()));return repo.find(p.id()).orElseThrow();}tx.executeWithoutResult(s->repo.transition(p.id(),PayoutStatus.FUNDS_HELD,PayoutStatus.SUBMITTED,holdId,result.providerCode(),result.providerReference(),null));wallet.settle(holdId,p.id(),amount,fee,currency.getCurrencyCode());tx.executeWithoutResult(s->repo.transition(p.id(),PayoutStatus.SUBMITTED,PayoutStatus.SUCCEEDED,holdId,null,null,null));return repo.find(p.id()).orElseThrow();}
 public PayoutView get(UUID id){return repo.find(id).orElseThrow(()->new IllegalArgumentException("payout not found"));}
 private byte[] hash(String v){try{return MessageDigest.getInstance("SHA-256").digest(v.getBytes(StandardCharsets.UTF_8));}catch(Exception e){throw new IllegalStateException(e);}}
}
