package com.qpay.payout.infrastructure;
import com.qpay.payout.application.PayoutView;import com.qpay.payout.domain.PayoutStatus;import com.qpay.payout.security.BankDataCrypto;import org.springframework.jdbc.core.simple.JdbcClient;import org.springframework.stereotype.Repository;
import java.time.*;import java.util.*;
@Repository public class PayoutRepository {
 private final JdbcClient jdbc;public PayoutRepository(JdbcClient jdbc){this.jdbc=jdbc;}
 public UUID createBeneficiary(UUID merchant,String reference,String name,String bank,String account,BankDataCrypto crypto){var encrypted=crypto.encrypt(account);UUID id=UUID.randomUUID();Instant now=Instant.now();jdbc.sql("""
 INSERT INTO beneficiary(id,merchant_id,beneficiary_reference,name,bank_code,account_ciphertext,account_nonce,account_key_version,account_mask,fingerprint,status,version,created_at,updated_at)
 VALUES(UUID_TO_BIN(:id,1),UUID_TO_BIN(:merchant,1),:reference,:name,:bank,:cipher,:nonce,:keyVersion,:mask,:fingerprint,'ACTIVE',0,:now,:now)
 """).param("id",id.toString()).param("merchant",merchant.toString()).param("reference",reference).param("name",name).param("bank",bank).param("cipher",encrypted.ciphertext()).param("nonce",encrypted.nonce()).param("keyVersion",encrypted.keyVersion()).param("mask",mask(account)).param("fingerprint",crypto.fingerprint(bank,account)).param("now",now).update();return id;}
 public Reservation createPayout(UUID merchant,UUID wallet,UUID beneficiary,String reference,long amount,long fee,String currency,String idem,byte[] hash){
  int claimed=jdbc.sql("INSERT IGNORE INTO idempotency_record(id,owner_id,operation,idempotency_key,request_hash,expires_at,created_at) VALUES(UUID_TO_BIN(:id,1),UUID_TO_BIN(:owner,1),'CREATE_PAYOUT',:key,:hash,TIMESTAMPADD(DAY,2,CURRENT_TIMESTAMP(6)),CURRENT_TIMESTAMP(6))").param("id",UUID.randomUUID().toString()).param("owner",merchant.toString()).param("key",idem).param("hash",hash).update();
  if(claimed==0){var old=jdbc.sql("SELECT request_hash,BIN_TO_UUID(resource_id,1) resource_id FROM idempotency_record WHERE owner_id=UUID_TO_BIN(:owner,1) AND operation='CREATE_PAYOUT' AND idempotency_key=:key").param("owner",merchant.toString()).param("key",idem).query((r,n)->new Old(r.getBytes(1),r.getString(2))).single();if(!Arrays.equals(old.hash,hash))throw new IllegalArgumentException("idempotency key payload conflict");if(old.resource==null)throw new IllegalStateException("payout request is processing");return new Reservation(find(UUID.fromString(old.resource)).orElseThrow(),true);}
  UUID id=UUID.randomUUID();Instant now=Instant.now();jdbc.sql("INSERT INTO payout(id,merchant_id,wallet_id,beneficiary_id,merchant_reference,amount_minor,fee_minor,currency,status,version,created_at,updated_at) VALUES(UUID_TO_BIN(:id,1),UUID_TO_BIN(:merchant,1),UUID_TO_BIN(:wallet,1),UUID_TO_BIN(:beneficiary,1),:reference,:amount,:fee,:currency,'CREATED',0,:now,:now)").param("id",id.toString()).param("merchant",merchant.toString()).param("wallet",wallet.toString()).param("beneficiary",beneficiary.toString()).param("reference",reference).param("amount",amount).param("fee",fee).param("currency",currency).param("now",now).update();jdbc.sql("INSERT INTO payout_saga(payout_id,saga_state,version,created_at,updated_at) VALUES(UUID_TO_BIN(:id,1),'CREATED',0,:now,:now)").param("id",id.toString()).param("now",now).update();jdbc.sql("UPDATE idempotency_record SET resource_id=UUID_TO_BIN(:id,1) WHERE owner_id=UUID_TO_BIN(:owner,1) AND operation='CREATE_PAYOUT' AND idempotency_key=:key").param("id",id.toString()).param("owner",merchant.toString()).param("key",idem).update();event(id,"payout.created.v1",now);return new Reservation(find(id).orElseThrow(),false);
 }
 public void transition(UUID id,PayoutStatus from,PayoutStatus to,UUID hold,String provider,String providerRef,String failure){from.requireTransitionTo(to);int changed=jdbc.sql("UPDATE payout SET status=:to,hold_id=COALESCE(UUID_TO_BIN(:hold,1),hold_id),provider_code=COALESCE(:provider,provider_code),provider_reference=COALESCE(:providerRef,provider_reference),failure_code=:failure,version=version+1,updated_at=CURRENT_TIMESTAMP(6),completed_at=IF(:terminal,CURRENT_TIMESTAMP(6),completed_at) WHERE id=UUID_TO_BIN(:id,1) AND status=:from").param("to",to.name()).param("hold",hold==null?null:hold.toString()).param("provider",provider).param("providerRef",providerRef).param("failure",failure).param("terminal",to==PayoutStatus.SUCCEEDED).param("id",id.toString()).param("from",from.name()).update();if(changed!=1)throw new IllegalStateException("concurrent or invalid payout transition");jdbc.sql("UPDATE payout_saga SET saga_state=:state,version=version+1,updated_at=CURRENT_TIMESTAMP(6) WHERE payout_id=UUID_TO_BIN(:id,1)").param("state",to.name()).param("id",id.toString()).update();event(id,"payout."+to.name().toLowerCase(Locale.ROOT).replace('_','-')+".v1",Instant.now());}
 public Optional<PayoutView> find(UUID id){return jdbc.sql("SELECT BIN_TO_UUID(id,1) id,BIN_TO_UUID(merchant_id,1) merchant_id,BIN_TO_UUID(wallet_id,1) wallet_id,BIN_TO_UUID(beneficiary_id,1) beneficiary_id,merchant_reference,amount_minor,fee_minor,currency,status,BIN_TO_UUID(hold_id,1) hold_id,provider_reference,failure_code,created_at,updated_at FROM payout WHERE id=UUID_TO_BIN(:id,1)").param("id",id.toString()).query((r,n)->new PayoutView(UUID.fromString(r.getString("id")),UUID.fromString(r.getString("merchant_id")),UUID.fromString(r.getString("wallet_id")),UUID.fromString(r.getString("beneficiary_id")),r.getString("merchant_reference"),r.getLong("amount_minor"),r.getLong("fee_minor"),Currency.getInstance(r.getString("currency")),PayoutStatus.valueOf(r.getString("status")),r.getString("hold_id")==null?null:UUID.fromString(r.getString("hold_id")),r.getString("provider_reference"),r.getString("failure_code"),r.getTimestamp("created_at").toInstant(),r.getTimestamp("updated_at").toInstant())).optional();}
 private void event(UUID id,String type,Instant now){jdbc.sql("INSERT INTO outbox_event(id,aggregate_id,event_type,partition_key,payload,occurred_at,publish_attempts) VALUES(UUID_TO_BIN(:event,1),UUID_TO_BIN(:id,1),:type,:key,JSON_OBJECT('payoutId',:key),:now,0)").param("event",UUID.randomUUID().toString()).param("id",id.toString()).param("type",type).param("key",id.toString()).param("now",now).update();}
 private String mask(String account){return "****"+account.substring(Math.max(0,account.length()-4));}
 public record Reservation(PayoutView payout,boolean replay){} private record Old(byte[] hash,String resource){}
}
