package com.qpay.user.api;
import com.qpay.user.application.*;import com.qpay.user.domain.KycStatus;import com.qpay.user.infrastructure.UserRepository;import jakarta.validation.Valid;import jakarta.validation.constraints.*;import org.springframework.http.*;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.security.core.annotation.AuthenticationPrincipal;import org.springframework.security.oauth2.jwt.Jwt;import org.springframework.web.bind.annotation.*;import java.util.UUID;
@RestController @RequestMapping("/api/v1/users") public class UserController {
 private final UserService service;public UserController(UserService service){this.service=service;}
 @PostMapping("/me") @ResponseStatus(HttpStatus.CREATED) UserView create(@AuthenticationPrincipal Jwt jwt,@Valid @RequestBody Profile r){return service.create(UUID.fromString(jwt.getClaimAsString("owner_id")),r.displayName(),r.email(),r.phone(),r.locale());}
 @GetMapping("/{id}") @PreAuthorize("@userAccess.canAccess(authentication,#id)") UserView get(@PathVariable UUID id){return service.get(id);}
 @PutMapping("/{id}") @PreAuthorize("@userAccess.canAccess(authentication,#id)") UserView update(@PathVariable UUID id,@Valid @RequestBody UpdateProfile r){return service.update(id,r.displayName(),r.email(),r.phone(),r.locale(),r.version());}
 @PostMapping("/{id}/kyc/{status}") @PreAuthorize("hasAnyRole('OPS','SUPER_ADMIN')") UserView kyc(@PathVariable UUID id,@PathVariable KycStatus status,@RequestBody KycRequest r){return service.kyc(id,status,r.reference());}
 @PostMapping("/{id}/devices") @PreAuthorize("@userAccess.canAccess(authentication,#id)") @ResponseStatus(HttpStatus.CREATED) UserRepository.DeviceRegistration device(@PathVariable UUID id,@Valid @RequestBody DeviceRequest r){return service.register(id,r.platform(),r.token());}
 @DeleteMapping("/{id}/devices/{deviceId}") @PreAuthorize("@userAccess.canAccess(authentication,#id)") @ResponseStatus(HttpStatus.NO_CONTENT) void revoke(@PathVariable UUID id,@PathVariable UUID deviceId){service.revoke(id,deviceId);}
 @PutMapping("/{id}/notification-preferences/{event}") @PreAuthorize("@userAccess.canAccess(authentication,#id)") @ResponseStatus(HttpStatus.NO_CONTENT) void preference(@PathVariable UUID id,@PathVariable String event,@RequestBody Preference r){service.preference(id,event,r.pushEnabled(),r.emailEnabled(),r.smsEnabled());}
 record Profile(@NotBlank String displayName,@Email String email,String phone,@NotBlank String locale){}record UpdateProfile(@NotBlank String displayName,@Email String email,String phone,@NotBlank String locale,@PositiveOrZero long version){}record KycRequest(String reference){}record DeviceRequest(@NotBlank String platform,@NotBlank String token){}record Preference(boolean pushEnabled,boolean emailEnabled,boolean smsEnabled){}
}
