package com.qpay.reconciliation.api;
import com.qpay.reconciliation.application.ReconciliationService;import jakarta.validation.Valid;import jakarta.validation.constraints.*;import org.springframework.http.*;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.security.core.annotation.AuthenticationPrincipal;import org.springframework.security.oauth2.jwt.Jwt;import org.springframework.web.bind.annotation.*;import org.springframework.web.multipart.MultipartFile;import java.io.IOException;import java.time.*;import java.util.UUID;
@RestController @RequestMapping("/api/v1/reconciliation") @PreAuthorize("hasAnyRole('FINANCE','OPS','SUPER_ADMIN')") public class ReconciliationController {
 private final ReconciliationService service;public ReconciliationController(ReconciliationService service){this.service=service;}
 @PostMapping(value="/runs",consumes=MediaType.MULTIPART_FORM_DATA_VALUE) @ResponseStatus(HttpStatus.ACCEPTED) RunResponse ingest(@RequestParam String providerCode,@RequestParam LocalDate settlementDate,@RequestPart MultipartFile file)throws IOException{if(file.isEmpty()||file.getSize()>10_000_000)throw new IllegalArgumentException("reconciliation file must contain 1 to 10,000,000 bytes");return new RunResponse(service.ingest(providerCode,settlementDate,file.getOriginalFilename(),file.getBytes()));}
 @PostMapping("/items/{itemId}/resolve") @ResponseStatus(HttpStatus.NO_CONTENT) void resolve(@PathVariable UUID itemId,@AuthenticationPrincipal Jwt jwt,@Valid @RequestBody ResolveRequest r){service.resolve(itemId,UUID.fromString(jwt.getSubject()),r.status(),r.reason());}
 @PostMapping("/internal-transactions") void internal(@Valid @RequestBody InternalRequest r){service.recordInternal(r.reference(),r.providerCode(),r.providerReference(),r.amountMinor(),r.currency(),r.status(),r.occurredAt());}
 record RunResponse(UUID runId){}record ResolveRequest(@NotBlank String status,@NotBlank @Size(max=500) String reason){}record InternalRequest(@NotBlank String reference,@NotBlank String providerCode,String providerReference,@Positive long amountMinor,@Size(min=3,max=3) String currency,@NotBlank String status,@NotNull Instant occurredAt){}
}
