package com.qpay.merchant.infrastructure;
import com.qpay.merchant.application.MerchantView;import com.qpay.merchant.domain.OnboardingStatus;import com.qpay.merchant.security.SecretProtector;import org.springframework.jdbc.core.simple.JdbcClient;import org.springframework.stereotype.Repository;import java.time.*;import java.util.*;
@Repository public class MerchantRepository {
 private final JdbcClient jdbc;public MerchantRepository(JdbcClient jdbc){this.jdbc=jdbc;}
 public MerchantView create(String legal,String display,String registration,String country,String currency){UUID id=UUID.randomUUID();Instant now=Instant.now();jdbc.sql("INSERT INTO merchant(id,legal_name,display_name,registration_number,country_code,status,kyb_status,default_currency,version,created_at,updated_at) VALUES(UUID_TO_BIN(:id,1),:legal,:display,:registration,:country,'PENDING','PENDING',:currency,0,:now,:now)").param("id",id.toString()).param("legal",legal).param("display",display).param("registration",registration).param("country",country).param("currency",currency).param("now",now).update();event(id,"merchant.onboarding-started.v1",now);return find(id).orElseThrow();}
 public MerchantView transition(UUID id,OnboardingStatus target){MerchantView current=lock(id);current.kybStatus().requireTransitionTo(target);String status=target==OnboardingStatus.APPROVED?"ACTIVE":target==OnboardingStatus.REJECTED?"REJECTED":current.status();jdbc.sql("UPDATE merchant SET kyb_status=:kyb,status=:status,version=version+1,updated_at=CURRENT_TIMESTAMP(6) WHERE id=UUID_TO_BIN(:id,1) AND version=:version").param("kyb",target.name()).param("status",status).param("id",id.toString()).param("version",current.version()).update();event(id,target==OnboardingStatus.APPROVED?"merchant.onboarding.completed.v1":"merchant.onboarding-updated.v1",Instant.now());return find(id).orElseThrow();}
 public ApiCredential createKey(UUID merchant,List<String> scopes,Instant expiry,SecretProtector protector){MerchantView view=lock(merchant);if(!"ACTIVE".equals(view.status()))throw new IllegalStateException("merchant must be active");String prefix=protector.randomToken(6),raw="qpk_"+prefix+"_"+protector.randomToken(32);UUID id=UUID.randomUUID();String json="[\""+String.join("\",\"",scopes)+"\"]";jdbc.sql("INSERT INTO merchant_api_key(id,merchant_id,key_prefix,secret_hash,scopes_json,status,expires_at,created_at) VALUES(UUID_TO_BIN(:id,1),UUID_TO_BIN(:merchant,1),:prefix,:hash,CAST(:scopes AS JSON),'ACTIVE',:expiry,CURRENT_TIMESTAMP(6))").param("id",id.toString()).param("merchant",merchant.toString()).param("prefix",prefix).param("hash",protector.hash(raw)).param("scopes",json).param("expiry",expiry).update();return new ApiCredential(id,prefix,raw,scopes,expiry);}
 public void revokeKey(UUID merchant,UUID key){int changed=jdbc.sql("UPDATE merchant_api_key SET status='REVOKED',revoked_at=CURRENT_TIMESTAMP(6) WHERE id=UUID_TO_BIN(:key,1) AND merchant_id=UUID_TO_BIN(:merchant,1) AND status='ACTIVE'").param("key",key.toString()).param("merchant",merchant.toString()).update();if(changed!=1)throw new IllegalArgumentException("active API key not found");}
 public void configureWebhook(UUID merchant,String url,SecretProtector.ProtectedSecret secret){jdbc.sql("UPDATE merchant SET webhook_url=:url,webhook_secret_ciphertext=:cipher,webhook_secret_nonce=:nonce,webhook_secret_key_version=:version,version=version+1,updated_at=CURRENT_TIMESTAMP(6) WHERE id=UUID_TO_BIN(:id,1)").param("url",url).param("cipher",secret.ciphertext()).param("nonce",secret.nonce()).param("version",secret.keyVersion()).param("id",merchant.toString()).update();}
 public Optional<MerchantView> find(UUID id){return jdbc.sql(select()+" WHERE id=UUID_TO_BIN(:id,1)").param("id",id.toString()).query(this::map).optional();}
 private MerchantView lock(UUID id){return jdbc.sql(select()+" WHERE id=UUID_TO_BIN(:id,1) FOR UPDATE").param("id",id.toString()).query(this::map).optional().orElseThrow(()->new IllegalArgumentException("merchant not found"));}
 private String select(){return "SELECT BIN_TO_UUID(id,1) id,legal_name,display_name,registration_number,country_code,status,kyb_status,default_currency,webhook_url,version,created_at,updated_at FROM merchant";}
 private MerchantView map(java.sql.ResultSet r,int n)throws java.sql.SQLException{return new MerchantView(UUID.fromString(r.getString("id")),r.getString("legal_name"),r.getString("display_name"),r.getString("registration_number"),r.getString("country_code"),r.getString("status"),OnboardingStatus.valueOf(r.getString("kyb_status")),Currency.getInstance(r.getString("default_currency")),r.getString("webhook_url"),r.getLong("version"),r.getTimestamp("created_at").toInstant(),r.getTimestamp("updated_at").toInstant());}
 private void event(UUID id,String type,Instant now){jdbc.sql("INSERT INTO outbox_event(id,aggregate_id,event_type,partition_key,payload,occurred_at,publish_attempts) VALUES(UUID_TO_BIN(:event,1),UUID_TO_BIN(:id,1),:type,:key,JSON_OBJECT('merchantId',:key),:now,0)").param("event",UUID.randomUUID().toString()).param("id",id.toString()).param("type",type).param("key",id.toString()).param("now",now).update();}
 public record ApiCredential(UUID id,String prefix,String secret,List<String> scopes,Instant expiresAt){}
}
